org.gradle.daemon=false
org.gradle.debug=false
org.gradle.jvmargs=-Xmx3G

mod_group_id=wtf.vd
mod_id=mek_factory_info
mod_name=Mekanism Factory Information
mod_license=LGPL-3.0
mod_version=0.1.0
mod_authors=vd
mod_description=Exposes Mekanism Factory tier Lines-count information to AE2 terminals, and adds a Lines-based sort order.
