pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = 'https://maven.minecraftforge.net/' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'mek-factory-info'

include 'neoforge-26.1.2'
include 'neoforge-1.21.1'
include 'forge-1.20.1'

project(':neoforge-26.1.2').projectDir = file('neoforge-26.1.2')
project(':neoforge-1.21.1').projectDir = file('neoforge-1.21.1')
project(':forge-1.20.1').projectDir = file('forge-1.20.1')
