plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        name = "Modmaven"
        url = "https://modmaven.dev/"
        content {
            includeGroup "mekanism"
        }
    }
}

dependencies {
    // Mekanism is a required dependency.
    compileOnly "mekanism:Mekanism:${mekanism_version_neoforge}"
    runtimeOnly "mekanism:Mekanism:${mekanism_version_neoforge}"
    // AE2 and Jade are optional dependencies.
    compileOnly "maven.modrinth:ae2:${ae2_version}"
    runtimeOnly "maven.modrinth:ae2:${ae2_version}"
    compileOnly "maven.modrinth:jade:${jade_version_neoforge}"
    runtimeOnly "maven.modrinth:jade:${jade_version_neoforge}"
}
